# Generated by Django 5.0 on 2023-12-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
