# Generated by Django 5.0 on 2023-12-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_groups_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
